# development configuration
# staging database configuration
DATABASE:
  - STAGING_DB:
      DBUSER : root
      DBPASSWORD : Z01011010$$mysqlroot
      DBHOST : localhost
      DBPORT : 3306
      DBNAME : sofanalysis_staging

  - TARGET_DB:
      DBUSER : root
      DBPASSWORD : Z01011010$$mysqlroot
      DBHOST : localhost
      DBPORT : 3306
      DBNAME : sofanalysis